In [77]:
import pandas as pd
df = pd.read_csv("salaries_by_college_major.csv")
df.head()
df.shape
df.columns
df.isna()
df.tail()
clean_df = df.dropna()
clean_df.tail()
clean_df["Starting Median Salary"].idxmax()
clean_df["Undergraduate Major"].loc[43]
clean_df["Mid-Career Median Salary"].idxmax()
clean_df["Undergraduate Major"].loc[8]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,"40,800.00","78,200.00","41,200.00","168,000.00",HASS
46,Psychology,"35,900.00","60,400.00","31,600.00","127,000.00",HASS
47,Religion,"34,100.00","52,000.00","29,700.00","96,400.00",HASS
48,Sociology,"36,500.00","58,200.00","30,700.00","118,000.00",HASS
49,Spanish,"34,000.00","53,100.00","31,000.00","96,400.00",HASS

In [34]:
print(clean_df["Mid-Career Median Salary"].max())
print(f"Index for the max Mid Career Median Salary: {clean_df["Mid-Career Median Salary"].idxmax()}")
print(clean_df["Undergraduate Major"][8])

107000.0
Index for the max Mid Career Median Salary: 8
Chemical Engineering

In [27]:
clean_df["Starting Median Salary"].min()
clean_df["Starting Median Salary"].idxmin()
clean_df.loc[49]

Undergraduate Major                  Spanish
Starting Median Salary               34000.0
Mid-Career Median Salary             53100.0
Mid-Career 10th Percentile Salary    31000.0
Mid-Career 90th Percentile Salary    96400.0
Group                                   HASS
Name: 49, dtype: object

In [38]:
print(clean_df["Starting Median Salary"].min())
print(f"Index of the lower starting median salary : {clean_df["Starting Median Salary"].idxmin()}")
print(clean_df["Undergraduate Major"][49])

34000.0
Index of the lower starting median salary : 49
Spanish

In [39]:
print(clean_df["Starting Median Salary"].min())
clean_df["Undergraduate Major"].loc[clean_df["Starting Median Salary"].idxmin()]

34000.0

'Spanish'

In [30]:
clean_df["Mid-Career Median Salary"].min()
clean_df["Mid-Career Median Salary"].idxmin()
clean_df.loc[18]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

In [43]:
clean_df.loc[clean_df["Mid-Career Median Salary"].idxmin()]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

In [50]:
clean_df["Mid-Career 90th Percentile Salary"]-clean_df["Mid-Career 10th Percentile Salary"]
spread_col = clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df["Mid-Career 10th Percentile Salary"])
#clean_df.insert( 1 , 'Spread', spread_col ), only can run once cause spread already inserted
clean_df.head()
low_risk = clean_df.sort_values("Spread")
low_risk[["Undergraduate Major", "Spread"]].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

In [56]:
# Pass the name of the column as a string to sort_values()
highest_values_df = clean_df.sort_values("Mid-Career 90th Percentile Salary", ascending=False)
highest_values_df[["Undergraduate Major", "Mid-Career 90th Percentile Salary"]].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [64]:
highest_spread = clean_df.sort_values("Spread", ascending = False)
highest_spread[["Undergraduate Major", "Spread"]].head()

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

In [73]:
clean_df.groupby("Group").count()
pd.options.display.float_format = "{:,.2f}".format
clean_df.groupby("Group").mean(numeric_only=True)

,Spread,Largest Difference in Salary,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,"103,958.33","-102,891.67","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","-92,177.27","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","-103,762.50","53,862.50","90,812.50","56,025.00","157,625.00"